-
  name: Setting up test LAMP stack project
  hosts: target2
  become: true
  vars:
    packages:
      - mariadb-server
      - firewalld
      - httpd
      - epel-release
      - python3-PyMySQL
      - php
      - php-mysqlnd
      - git
    services:
      - firewalld
      - httpd
      - mariadb
    ports:
      - 3306/tcp
      - 80/tcp
  tasks:
    - name: Install Pre-requisites
      yum:
        name: '{{ item }}'
        state: installed
      loop: '{{ packages }}'
    - name: Start and enable services
      service:
        name: '{{ item }}'
        state: started
        enabled: yes
      loop: '{{ services }}'

    - name: Configuring firewalld
      firewalld:
        zone: public
        port: '{{ item }}'
        permanent: true
        state: enabled
      loop: '{{ ports }}'
    - name: Reload firewalld
      systemd:
        name: firewalld
        state: reloaded

    - name: Create MySQL Database
      mysql_db:
        name: ecomdb
        state: present
    - name: Create database user and configure privileges
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL'
        host: localhost
        state: present

    - name: Create db load script
      copy:
        dest: /home/osboxes/db-load-script.sql
        content: |
            USE ecomdb;
            CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
            INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");
    - name: Run DB load script
      mysql_db:
        name: ecomdb
        state: import
        target: /home/osboxes/db-load-script.sql

    - name: Configure httpd
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'index.html'
        replace: 'index.php'

    - name: Clone the git repo
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/

    - name: Update index.php
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: 'localhost'
